name: 'meeshkan'

description: 'Run tests given an OpenAPI schema'

branding:
  icon: 'wind'
  color: 'red'

inputs:
  endpoint: # id of input
    description: 'Location of the OpenAPI schema to test'
    required: true
    default: 'http://localhost:8080'

outputs:
  meeshkan_time: # id of output
    description: 'The time we greeted you'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.endpoint }}
  env:
    MEESHKAN_TEST: value1
    MEESHKAN_ENDPOINT: ${{ inputs.endpoint }}

