name: 'Meeshkan'

description: 'Run Meeshkan test runs against a service'

branding:
  icon: 'wind'
  color: 'red'

inputs:
  client_id:
    description: 'The project client ID obtained from the Meeshkan webapp'
    required: true
    default: 'http://localhost:8080'
  client_secret:
    description: 'A secret token obtained from the Meeshkan webapp'
    required: true
  url:
    description: 'The URL that Meeshkan will test'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    MEESHKAN_CLIENT_ID: ${{ inputs.client_id }}
    MEESHKAN_CLIENT_SECRET: ${{ inputs.client_secret }}
    MEESHKAN_URL: ${{ inputs.url }}
