#!/usr/bin/env python3

import os
import requests

MEESHKAN_CLIENT_ID = os.environ["MEESHKAN_CLIENT_ID"]
MEESHKAN_CLIENT_SECRET = os.environ["MEESHKAN_CLIENT_ID"]
MEESHKAN_URL = os.environ["MEESHKAN_URL"]

print(f"MEESHKAN_CLIENT_ID = {MEESHKAN_CLIENT_ID}, MEESHKAN_CLIENT_SECRET={MEESHKAN_CLIENT_SECRET}, MEESHKAN_URL={MEESHKAN_URL}")
